<?php

namespace App\Modules\BaseApp\Enums;

abstract class ResourceTypes
{
    const USER = 'user',
          Agent = 'agent',
          PAGE = 'page',
        NEWS = 'news',
        GARBAGE_MEDIA = 'garbage_media',
        CATEGORIES = 'categories',
        AREAS = 'areas',
        FINISHEDAREAS = 'finished',
        UNFINISHEDAREAS = 'unfinished',
        SEMIFINISHEDAREAS = 'semi-finished',
        PROJECTS = 'projects',
        COUNTRY = 'country',
        Calculator = 'Calculator',
        HOMEPAGE = 'home_page',
        MOBILE_HOMEPAGE = 'mobile_home_page',
        PROPERTIES_LIST = 'properties_list',
        CONTACTINFO = 'contact_info',
        NEWS_META_TAGS = 'news_meta_tags',
        PAGE_META_TAGS = 'page_meta_tags',
        ON_BOARDING_SCREEN = 'on_boarding_screen' ,
        NEWS_TELLER = 'news_teller' ,
        MORTGAGE_APPLICATION = 'mortgage_application' ,
        CATEGORY_META_TAGS = 'category_meta_tags',
        VisionAndMission = 'vision_mission',
        OurTeam = 'our_team',
        SHAREHOLDERS = 'shareholders',
        Subsidiaries = 'subsidiaries',
        PROJECTGALLERY = 'gallery',
        SubsidiariesIMAGES = 'Subsidiaries_images',
        SHAREHOLDERIMAGES = 'shareholder_images',
        UNITS = 'units',
        UNITSIMAGES = 'units_images',
        SOCIALLINKS = 'social_links',
        HOWITWORKS = 'how_it_works',
        FILTER  =   "filters",
        SLIDER  =   "sliders",
        PROPERTY_TYPE  =  "property_type",
        UNIT_TYPE  =  "unit_type",
        MORTGAGE_LOOKUPS  =  "mortgage_lookups",
        LOOKUP  =  "lookup",
        GENDER  =  "gender",
        MARITAL_STATUS  =  "marital_status",
        WORK_TYPES  =  "work_types",
        NATIONALITY = "nationality",
        PARTNERS="Partners",
        PRODUCTS="Products",
        USER_OVERVIEW="user_overview",
        USER_LOANS="user_loans",
        USER_APPLICATION="user_applications",
        USER_INSTALLEMENTS="user_installements",
        NEXT_REMINDER="next_reminder",
        USER_REQUESTS="user_requests",
        Iframe_Url="Iframe Url",
        Payment_Methods="Payment Methods",
        EXTRRA_DOCUMENTS="Extra Documents",
        NTIFICATION="Notification"
    ;

}
