name: Laravel

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  tests:

    runs-on: ubuntu-latest


    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '7.3'
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
  build:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout
        uses: actions/checkout@v2


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deployment
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.ARCH_TESTING_IP }}
          username: ${{ secrets.ARCH_TESTING_USER }}
          key: ${{ secrets.ARCH_TESTING_KEY }} 
          script: |
            whoami
            ls -la
            cd /home/fleetexpress/af-egypt.fleet-express.com
            git pull origin master
            chmod -R 777 storage bootstrap/cache
